services:

  api-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: reading
    ports:
      - 27017:27017

  server:
    build: .
    depends_on:
      - api-db
    ports:
      - 8080:8080
    links:
      - api-db
