version: "2"

services:

  api-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: reading
    ports:
      - 27017:27017

  mongo-seed:
    image: mongo
    links:
      - api-db
    volumes:
      - ./infra/mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh

  reading-app:
    build: .
    depends_on:
      - api-db
    ports:
      - 8080:8080
    links:
      - api-db
